# Generated by Django 3.2.23 on 2024-02-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company_size',
            field=models.IntegerField(default=1),
        ),
    ]
